pipeline {
    agent any

  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }
  }

   stage('Package') {
      steps {
        script {
          sh 'echo "Package App"'
        }
      }
    }
  }

   stage('Deploy') {
      steps {
        script {
          sh 'echo "Deploy App"'
        }
      }
    }
  }

   stage('Clean Up') {
      steps {
        script {
          sh 'echo "Cleanup"'
        }
      }
    }
  }
}