pipeline {
    agent any
    parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }

    environment {
      ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }

  stages {
    stage('Initial Cleanup') {
      steps{
        dir("${WORKSPACE}") {
          deleteDir()
        }
      }
    }

    stage('SCM Checkout'){
      steps{
       git 'https://github.com/brpo01/ansible-config-mgt.git'
      }
    }

    stage('Execute Ansible Playbook'){
      steps{
        ansiblePlaybook credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yml'
      }
    }

    stage('Clean Workspace'){
      steps{
        cleanWs()
      }
    }
  }
}